---
- hosts: all
  tasks:
    - name: Testing role installation: {{ cookiecutter.galaxy_fq_name }}
      ansible.builtin.include_role:
        name: '{% raw %}{{ playbook_dir }}{% endraw %}'
    - name: Executing '{{ cookiecutter.role_name }} --version'
      ansible.builtin.command: {{ cookiecutter.role_name }} --version
      register: '{{ cookiecutter.role_name }}_test_output'
    - name: Output from '{{ cookiecutter.role_name }} --version'
      ansible.builtin.debug:
        msg: {% raw %}'{{ {% endraw %}{{ cookiecutter.role_name }}_test_output.stdout{% raw %} }}'{% endraw %}
